### ISSUE TITLE
App milestones

### ISSUE THREAD

**Issue by alexellis** [alexellis/growlab#15]
Done:
- [x] Capture an image from the Pi Camera
- [x] Capture BME280 sensor data
- [x] Annotate the image with a transparency background
- [x] Create HTML preview page and thumbnail
- [x] Offer script to commit the preview to GitHub Pages
- [x] Run in single-shot mode

Remaining:
- [ ] Run in the background as a daemon / systemd service taking photos every N minutes
- [ ] Save images into a folders ordered by date like [phototimer does](https://github.com/alexellis/phototimer)
- [ ] Cancel shooting outside of preset hours, see [phototimer](https://github.com/alexellis/phototimer)

Stretch goals:
- [ ] Tutorial for InfluxDB
- [ ] Update app to push BME280 data into InfluxDB
- [ ] Exported dashboard.json for Grafana

See also: https://github.com/alexellis/enviro-dashboard
